# Generated by Django 2.2 on 2020-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20200702_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(default=0),
        ),
    ]
